version: "3"
# 管理的服务
services:
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
        # 环境变量
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - "${MYSQL_DIR}/data:/var/lib/mysql"
            - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
            - "${MYSQL_DIR}/my.cnf:/etc/mysql/my.cnf"
            - "${MYSQL_DIR}/mysql-files:/var/lib/mysql-files"